#!/bin/bash

sudo docker build --rm -t bepsoccer/all-in-one-hackazon .
sudo docker run --name hackazon -d -p 80:80 bepsoccer/all-in-one-hackazon

sleep 7s

sudo docker logs hackazon | grep "password"
